package com.shoplane.services;

import java.util.List;
import java.util.Properties;

import javax.mail.Authenticator;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

import com.shoplane.models.Bill;
import com.shoplane.models.Order;
import com.shoplane.models.User;
import com.shoplane.utils.Helper;

public class SendMail {
  public SendMail() {
  }

  public boolean sendOTPSignUpAccount(User user) {
    boolean isSend = false;
    String toEmail = user.getEmail();
    String fromEmail = "doduongthaituan201102@gmail.com";
    String fromPwd = "ccfpewhvraqeghqj";
	/*
	 * String fromEmail = "20110743@student.hcmute.edu.vn"; String fromPwd =
	 * "Tuanvn1234567890..";
	 */    try {

      // your host email smtp server details
      Properties pr = new Properties();
      pr.setProperty("mail.smtp.host", "smtp.gmail.com");
      pr.setProperty("mail.smtp.port", "587");
      pr.setProperty("mail.smtp.auth", "true");
      pr.setProperty("mail.smtp.starttls.enable", "true");
      pr.put("mail.smtp.ssl.trust", "smtp.gmail.com");

      // get session to authenticate the host email address and password
      Session session = Session.getInstance(pr, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
          return new PasswordAuthentication(fromEmail, fromPwd);
        }
      });

      // set email message details
      Message mess = new MimeMessage(session);

      // set from email address
      mess.setFrom(new InternetAddress(fromEmail));
      // set to email address or destination email address
      mess.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));

      // set email subject
      mess.setSubject("User Email Verification");

      // set message text
      mess.setContent("<!doctype html>\r\n"
          + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
          + "\r\n"
          + "<head>\r\n"
          + "    <title>\r\n"
          + "\r\n"
          + "    </title>\r\n"
          + "    <!--[if !mso]><!-- -->\r\n"
          + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
          + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        #outlook a {\r\n"
          + "            padding: 0;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ReadMsgBody {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass * {\r\n"
          + "            line-height: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        body {\r\n"
          + "            margin: 0;\r\n"
          + "            padding: 0;\r\n"
          + "            -webkit-text-size-adjust: 100%;\r\n"
          + "            -ms-text-size-adjust: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        table,\r\n"
          + "        td {\r\n"
          + "            border-collapse: collapse;\r\n"
          + "            mso-table-lspace: 0pt;\r\n"
          + "            mso-table-rspace: 0pt;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        img {\r\n"
          + "            border: 0;\r\n"
          + "            height: auto;\r\n"
          + "            line-height: 100%;\r\n"
          + "            outline: none;\r\n"
          + "            text-decoration: none;\r\n"
          + "            -ms-interpolation-mode: bicubic;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        p {\r\n"
          + "            display: block;\r\n"
          + "            margin: 13px 0;\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--[if !mso]><!-->\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (max-width:480px) {\r\n"
          + "            @-ms-viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "            @viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <!--[if mso]>\r\n"
          + "        <xml>\r\n"
          + "        <o:OfficeDocumentSettings>\r\n"
          + "          <o:AllowPNG/>\r\n"
          + "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
          + "        </o:OfficeDocumentSettings>\r\n"
          + "        </xml>\r\n"
          + "        <![endif]-->\r\n"
          + "    <!--[if lte mso 11]>\r\n"
          + "        <style type=\"text/css\">\r\n"
          + "          .outlook-group-fix { width:100% !important; }\r\n"
          + "        </style>\r\n"
          + "        <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (min-width:480px) {\r\n"
          + "            .mj-column-per-100 {\r\n"
          + "                width: 100% !important;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "</head>\r\n"
          + "\r\n"
          + "<body style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "    <div style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#f9f9f9;background-color:#f9f9f9;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#f9f9f9;background-color:#f9f9f9;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border-bottom:#333957 solid 5px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#fff;background-color:#fff;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#fff;background-color:#fff;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border:#dddddd solid 1px;border-top:0px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:bottom;\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
          + "                                                <tbody>\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td style=\"width:64px;\">\r\n"
          + "\r\n"
          + "                                                            <img height=\"auto\" src=\"https://i.imgur.com/KO1vcE9.png\" style=\"border:0;display:block;outline:none;text-decoration:none;width:100%;\" width=\"64\" />\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "                                                </tbody>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;padding-bottom:40px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:22px;font-weight:bold;line-height:1;text-align:center;color:#555;\">\r\n"
          + "                                                User Email Verification\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:16px;line-height:22px;text-align:left;color:#555;\">\r\n"
          + "                                                Registered successfully. Please verify your account using this code: "
          + user.getCode()
          + "\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                  \r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:14px;line-height:20px;text-align:left;color:#525252;\">\r\n"
          + "                                                Best regards,<br><br>Do Duong Thai Tuan<br>Shoplane Company, CEO and Founder<br>\r\n"
          + "                                               \r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "                                    <tbody>\r\n"
          + "                                        <tr>\r\n"
          + "                                            <td style=\"vertical-align:bottom;padding:0;\">\r\n"
          + "\r\n"
          + "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td align=\"center\" style=\"font-size:0px;padding:0;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:300;line-height:1;text-align:center;color:#575757;\">\r\n"
          + "                                                                Some Firm Ltd, 35 Avenue. City 10115, USA\r\n"
          + "                                                            </div>\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td align=\"center\" style=\"font-size:0px;padding:10px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:300;line-height:1;text-align:center;color:#575757;\">\r\n"
          + "                                                                <a href=\"\" style=\"color:#575757\">Unsubscribe</a> from our emails\r\n"
          + "                                                            </div>\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "\r\n"
          + "                                                </table>\r\n"
          + "\r\n"
          + "                                            </td>\r\n"
          + "                                        </tr>\r\n"
          + "                                    </tbody>\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    </div>\r\n"
          + "\r\n"
          + "</body>\r\n"
          + "\r\n"
          + "</html>", "text/html; charset=UTF-8");
      // send the message
      Transport.send(mess);

      isSend = true;

    } catch (Exception e) {
      e.printStackTrace();
    }
    return isSend;
  }

  // send reset password
  public boolean sendResetPassword(String toEmail, String code) {
    boolean isSend = false;

    /*
     * String fromEmail = "doduongthaituan201102@gmail.com";
     * String fromPwd = "ddqzmkydrtjexbfj";
     */
    String fromEmail = "doduongthaituan201102@gmail.com";
    String fromPwd = "ccfpewhvraqeghqj";
    try {

      // your host email smtp server details
      Properties pr = new Properties();
      pr.setProperty("mail.smtp.host", "smtp.gmail.com");
      pr.setProperty("mail.smtp.port", "587");
      pr.setProperty("mail.smtp.auth", "true");
      pr.setProperty("mail.smtp.starttls.enable", "true");
      pr.put("mail.smtp.ssl.trust", "smtp.gmail.com");

      // get session to authenticate the host email address and password
      Session session = Session.getInstance(pr, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
          return new PasswordAuthentication(fromEmail, fromPwd);
        }
      });

      // set email message details
      Message mess = new MimeMessage(session);

      // set from email address
      mess.setFrom(new InternetAddress(fromEmail));
      // set to email address or destination email address
      mess.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));

      // set email subject
      mess.setSubject("Password change request");

      // set message content
      mess.setContent("<!doctype html>\r\n"
          + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
          + "\r\n"
          + "<head>\r\n"
          + "    <title>\r\n"
          + "\r\n"
          + "    </title>\r\n"
          + "    <!--[if !mso]><!-- -->\r\n"
          + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
          + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        #outlook a {\r\n"
          + "            padding: 0;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ReadMsgBody {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass * {\r\n"
          + "            line-height: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        body {\r\n"
          + "            margin: 0;\r\n"
          + "            padding: 0;\r\n"
          + "            -webkit-text-size-adjust: 100%;\r\n"
          + "            -ms-text-size-adjust: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        table,\r\n"
          + "        td {\r\n"
          + "            border-collapse: collapse;\r\n"
          + "            mso-table-lspace: 0pt;\r\n"
          + "            mso-table-rspace: 0pt;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        img {\r\n"
          + "            border: 0;\r\n"
          + "            height: auto;\r\n"
          + "            line-height: 100%;\r\n"
          + "            outline: none;\r\n"
          + "            text-decoration: none;\r\n"
          + "            -ms-interpolation-mode: bicubic;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        p {\r\n"
          + "            display: block;\r\n"
          + "            margin: 13px 0;\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--[if !mso]><!-->\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (max-width:480px) {\r\n"
          + "            @-ms-viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "            @viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <!--[if mso]>\r\n"
          + "        <xml>\r\n"
          + "        <o:OfficeDocumentSettings>\r\n"
          + "          <o:AllowPNG/>\r\n"
          + "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
          + "        </o:OfficeDocumentSettings>\r\n"
          + "        </xml>\r\n"
          + "        <![endif]-->\r\n"
          + "    <!--[if lte mso 11]>\r\n"
          + "        <style type=\"text/css\">\r\n"
          + "          .outlook-group-fix { width:100% !important; }\r\n"
          + "        </style>\r\n"
          + "        <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (min-width:480px) {\r\n"
          + "            .mj-column-per-100 {\r\n"
          + "                width: 100% !important;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "</head>\r\n"
          + "\r\n"
          + "<body style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "    <div style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#f9f9f9;background-color:#f9f9f9;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#f9f9f9;background-color:#f9f9f9;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border-bottom:#333957 solid 5px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#fff;background-color:#fff;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#fff;background-color:#fff;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border:#dddddd solid 1px;border-top:0px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:bottom;\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
          + "                                                <tbody>\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td style=\"width:64px;\">\r\n"
          + "\r\n"
          + "                                                            <img height=\"auto\" src=\"https://i.imgur.com/KO1vcE9.png\" style=\"border:0;display:block;outline:none;text-decoration:none;width:100%;\" width=\"64\" />\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "                                                </tbody>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;padding-bottom:40px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:38px;font-weight:bold;line-height:1;text-align:center;color:#555;\">\r\n"
          + "                                                OTP Verification\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;padding-bottom:40px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:18px;line-height:1;text-align:center;color:#555;\">\r\n"
          + "                                               Please use the following One Time Password (OTP) to reset your account: "
          + code + ". Do not share this OTP with anyone!!. Thank you!\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
          + "                                                <tbody>\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td style=\"width:128px;\">\r\n"
          + "\r\n"
          + "                                                            <img height=\"auto\" src=\"https://i.imgur.com/247tYSw.png\" style=\"border:0;display:block;outline:none;text-decoration:none;width:100%;\" width=\"128\" />\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "                                                </tbody>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "        </div>\r\n"
          + "    </div>\r\n"
          + "\r\n"
          + "</body>\r\n"
          + "\r\n"
          + "</html>", "text/html; charset=UTF-8");
      // send the message
      Transport.send(mess);
      isSend = true;
    } catch (Exception e) {
      e.printStackTrace();
    }
    return isSend;
  }

  // Create table bill detail
  private String createBilDetail(Bill bill) {
    String html = "";
    List<Order> orders = bill.getOrders();
    for (Order order : orders) {
      html += " <tr>\r\n"
          + "<td style=\"padding: 5px 15px 5px 0;\">" + order.getOption().getProduct().getProductName() + "</td>\r\n"
          + "<td style=\"padding: 0 15px;\">" + order.getOrderedQuantity() + "</td>\r\n"
          + "<td style=\"padding: 0 0 0 15px;\" align=\"right\">" + Helper.intToVND(order.getPrice()) + "</td>\r\n"
          + "</tr>";
    }
    // Total row
    html += " <tr style=\"border-bottom:2px solid #ecedee;text-align:left;padding:15px 0;\">\r\n"
        + "<td style=\"padding: 5px 15px 5px 0; font-weight:bold\">TOTAL</td>\r\n"
        + "<td style=\"padding: 0 15px;\"></td>"
        + "<td style=\"padding: 0 0 0 15px; font-weight:bold\" align=\"right\">" + Helper.intToVND(bill.getTotalPrice())
        + "</td>\r\n"
        + "</tr>";
    return html;
  }

  // Send bill
  public boolean sendReceipt(String toEmail, Bill bill) {
    boolean isSend = false;

    // Source mail
    String fromEmail = "doduongthaituan201102@gmail.com";
    String fromPwd = "ccfpewhvraqeghqj";
    try {

      // your host email smtp server details
      Properties pr = new Properties();
      pr.setProperty("mail.smtp.host", "smtp.gmail.com");
      pr.setProperty("mail.smtp.port", "587");
      pr.setProperty("mail.smtp.auth", "true");
      pr.setProperty("mail.smtp.starttls.enable", "true");
      pr.put("mail.smtp.ssl.trust", "smtp.gmail.com");

      // get session to authenticate the host email address and password
      Session session = Session.getInstance(pr, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
          return new PasswordAuthentication(fromEmail, fromPwd);
        }
      });

      // set email message details
      Message mess = new MimeMessage(session);

      // set from email address
      mess.setFrom(new InternetAddress(fromEmail));
      // set to email address or destination email address
      mess.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));

      // set email subject
      mess.setSubject("Đơn đặt hàng của bạn");

      // set context html
      mess.setContent("<!doctype html>\r\n"
          + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
          + "\r\n"
          + "<head>\r\n"
          + "    <title>\r\n"
          + "\r\n"
          + "    </title>\r\n"
          + "    <!--[if !mso]><!-- -->\r\n"
          + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
          + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        #outlook a {\r\n"
          + "            padding: 0;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ReadMsgBody {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass * {\r\n"
          + "            line-height: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        body {\r\n"
          + "            margin: 0;\r\n"
          + "            padding: 0;\r\n"
          + "            -webkit-text-size-adjust: 100%;\r\n"
          + "            -ms-text-size-adjust: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        table,\r\n"
          + "        td {\r\n"
          + "            border-collapse: collapse;\r\n"
          + "            mso-table-lspace: 0pt;\r\n"
          + "            mso-table-rspace: 0pt;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        img {\r\n"
          + "            border: 0;\r\n"
          + "            height: auto;\r\n"
          + "            line-height: 100%;\r\n"
          + "            outline: none;\r\n"
          + "            text-decoration: none;\r\n"
          + "            -ms-interpolation-mode: bicubic;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        p {\r\n"
          + "            display: block;\r\n"
          + "            margin: 13px 0;\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--[if !mso]><!-->\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (max-width:480px) {\r\n"
          + "            @-ms-viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "            @viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <!--[if mso]>\r\n"
          + "        <xml>\r\n"
          + "        <o:OfficeDocumentSettings>\r\n"
          + "          <o:AllowPNG/>\r\n"
          + "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
          + "        </o:OfficeDocumentSettings>\r\n"
          + "        </xml>\r\n"
          + "        <![endif]-->\r\n"
          + "    <!--[if lte mso 11]>\r\n"
          + "        <style type=\"text/css\">\r\n"
          + "          .outlook-group-fix { width:100% !important; }\r\n"
          + "        </style>\r\n"
          + "        <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (min-width:480px) {\r\n"
          + "            .mj-column-per-100 {\r\n"
          + "                width: 100% !important;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "</head>\r\n"
          + "\r\n"
          + "<body style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "    <div style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#f9f9f9;background-color:#f9f9f9;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#f9f9f9;background-color:#f9f9f9;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border-bottom:#333957 solid 5px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#fff;background-color:#fff;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#fff;background-color:#fff;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border:#dddddd solid 1px;border-top:0px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:bottom;\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
          + "                                                <tbody>\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td style=\"width:64px;\">\r\n"
          + "\r\n"
          + "                                                            <img height=\"auto\" src=\"https://i.imgur.com/KO1vcE9.png\" style=\"border:0;display:block;outline:none;text-decoration:none;width:100%;\" width=\"64\" />\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "                                                </tbody>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:24px;font-weight:bold;line-height:22px;text-align:center;color:#525252;\">\r\n"
          + "                                              Thank you for your order.\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:14px;line-height:22px;text-align:left;color:#525252;\">\r\n"
          + "                                                <p>Hi " + toEmail + ",</p>\r\n"
          + "                                                <p>We appreciate your order. This email confirms that we are preparing it at this very moment and will confirm shipping details within the next few hours.</p>\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table 0=\"[object Object]\" 1=\"[object Object]\" 2=\"[object Object]\" border=\"0\" style=\"cellspacing:0;color:#000;font-family:'Helvetica Neue',Arial,sans-serif;font-size:13px;line-height:22px;table-layout:auto;width:100%;\">\r\n"
          + "                                                <tr style=\"border-bottom:1px solid #ecedee;text-align:left;\">\r\n"
          + "                                                    <th style=\"padding: 0 15px 10px 0;\">Product</th>\r\n"
          + "                                                    <th style=\"padding: 0 15px;\">Quantity</th>\r\n"
          + "                                                    <th style=\"padding: 0 0 0 15px;\" align=\"right\">Price</th>\r\n"
          + "                                                </tr>\r\n"
          + createBilDetail(bill)
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "                                   \r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:14px;line-height:20px;text-align:left;color:#525252;\">\r\n"
          + "                                                Best regards,<br><br>Do Duong Thai Tuan<br>Shoplane Company, CEO and Founder<br>\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "                                    <tbody>\r\n"
          + "                                        <tr>\r\n"
          + "                                            <td style=\"vertical-align:bottom;padding:0;\">\r\n"
          + "\r\n"
          + "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td align=\"center\" style=\"font-size:0px;padding:0;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:300;line-height:1;text-align:center;color:#575757;\">\r\n"
          + "                                                                153/1, Vo Van Ngan, Linh Chieu, Thu Duc, Ho Chi Minh\r\n"
          + "                                                            </div>\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "\r\n"
          + "                                                </table>\r\n"
          + "\r\n"
          + "                                            </td>\r\n"
          + "                                        </tr>\r\n"
          + "                                    </tbody>\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    </div>\r\n"
          + "\r\n"
          + "</body>\r\n"
          + "\r\n"
          + "</html>", "text/html; charset=UTF-8");
      // send the message
      Transport.send(mess);

      isSend = true;

    } catch (Exception e) {
      e.printStackTrace();
    }
    return isSend;
  }

  // send email wellcome signup success
  public boolean sendSignUpSuccess(String toEmail, String loginUrl) {
    boolean isSend = false;

    // Source mail
    String fromEmail = "doduongthaituan201102@gmail.com";
    String fromPwd = "ccfpewhvraqeghqj";
    try {

      // your host email smtp server details
      Properties pr = new Properties();
      pr.setProperty("mail.smtp.host", "smtp.gmail.com");
      pr.setProperty("mail.smtp.port", "587");
      pr.setProperty("mail.smtp.auth", "true");
      pr.setProperty("mail.smtp.starttls.enable", "true");
      pr.put("mail.smtp.ssl.trust", "smtp.gmail.com");

      // get session to authenticate the host email address and password
      Session session = Session.getInstance(pr, new Authenticator() {
        @Override
        protected PasswordAuthentication getPasswordAuthentication() {
          return new PasswordAuthentication(fromEmail, fromPwd);
        }
      });

      // set email message details
      Message mess = new MimeMessage(session);

      // set from email address
      mess.setFrom(new InternetAddress(fromEmail));
      // set to email address or destination email address
      mess.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));

      // set email subject
      mess.setSubject("Thank you for SignUp for SHOPLANE");

      // set context html
      mess.setContent("<!doctype html>\r\n"
          + "<html xmlns=\"http://www.w3.org/1999/xhtml\" xmlns:v=\"urn:schemas-microsoft-com:vml\" xmlns:o=\"urn:schemas-microsoft-com:office:office\">\r\n"
          + "\r\n"
          + "<head>\r\n"
          + "    <title>\r\n"
          + "\r\n"
          + "    </title>\r\n"
          + "    <!--[if !mso]><!-- -->\r\n"
          + "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n"
          + "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        #outlook a {\r\n"
          + "            padding: 0;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ReadMsgBody {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass {\r\n"
          + "            width: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        .ExternalClass * {\r\n"
          + "            line-height: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        body {\r\n"
          + "            margin: 0;\r\n"
          + "            padding: 0;\r\n"
          + "            -webkit-text-size-adjust: 100%;\r\n"
          + "            -ms-text-size-adjust: 100%;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        table,\r\n"
          + "        td {\r\n"
          + "            border-collapse: collapse;\r\n"
          + "            mso-table-lspace: 0pt;\r\n"
          + "            mso-table-rspace: 0pt;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        img {\r\n"
          + "            border: 0;\r\n"
          + "            height: auto;\r\n"
          + "            line-height: 100%;\r\n"
          + "            outline: none;\r\n"
          + "            text-decoration: none;\r\n"
          + "            -ms-interpolation-mode: bicubic;\r\n"
          + "        }\r\n"
          + "\r\n"
          + "        p {\r\n"
          + "            display: block;\r\n"
          + "            margin: 13px 0;\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--[if !mso]><!-->\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (max-width:480px) {\r\n"
          + "            @-ms-viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "            @viewport {\r\n"
          + "                width: 320px;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "    <!--<![endif]-->\r\n"
          + "    <!--[if mso]>\r\n"
          + "        <xml>\r\n"
          + "        <o:OfficeDocumentSettings>\r\n"
          + "          <o:AllowPNG/>\r\n"
          + "          <o:PixelsPerInch>96</o:PixelsPerInch>\r\n"
          + "        </o:OfficeDocumentSettings>\r\n"
          + "        </xml>\r\n"
          + "        <![endif]-->\r\n"
          + "    <!--[if lte mso 11]>\r\n"
          + "        <style type=\"text/css\">\r\n"
          + "          .outlook-group-fix { width:100% !important; }\r\n"
          + "        </style>\r\n"
          + "        <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "        @media only screen and (min-width:480px) {\r\n"
          + "            .mj-column-per-100 {\r\n"
          + "                width: 100% !important;\r\n"
          + "            }\r\n"
          + "        }\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "\r\n"
          + "    <style type=\"text/css\">\r\n"
          + "    </style>\r\n"
          + "\r\n"
          + "</head>\r\n"
          + "\r\n"
          + "<body style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "    <div style=\"background-color:#f9f9f9;\">\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#f9f9f9;background-color:#f9f9f9;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#f9f9f9;background-color:#f9f9f9;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border-bottom:#333957 solid 5px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"background:#fff;background-color:#fff;Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"background:#fff;background-color:#fff;width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"border:#dddddd solid 1px;border-top:0px;direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"vertical-align:bottom;\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:collapse;border-spacing:0px;\">\r\n"
          + "                                                <tbody>\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td style=\"width:64px;\">\r\n"
          + "\r\n"
          + "                                                            <img height=\"auto\" src=\"https://i.imgur.com/KO1vcE9.png\" style=\"border:0;display:block;outline:none;text-decoration:none;width:100%;\" width=\"64\" />\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "                                                </tbody>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;padding-bottom:40px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:28px;font-weight:bold;line-height:1;text-align:center;color:#555;\">\r\n"
          + "                                                Welcome to SHOPLANE\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:16px;line-height:22px;text-align:left;color:#555;\">\r\n"
          + "                                                Hello " + toEmail + "!<br></br>\r\n"
          + "                                                Thank you for signing up for SHOPLANE Company. We're really happy to have you! Click the link below to login to your account:\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"center\" style=\"font-size:0px;padding:10px 25px;padding-top:30px;padding-bottom:50px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"border-collapse:separate;line-height:100%;\">\r\n"
          + "                                                <tr>\r\n"
          + "                                                    <td align=\"center\" bgcolor=\"#2F67F6\" role=\"presentation\" style=\"border:none;border-radius:3px;color:#ffffff;cursor:auto;padding:15px 25px;\" valign=\"middle\">\r\n"
          + "                                                        <a href=\"" + loginUrl
          + "\" style=\"background:#2F67F6;color:#ffffff;font-family:'Helvetica Neue',Arial,sans-serif;font-size:15px;font-weight:normal;line-height:120%;Margin:0;text-decoration:none;text-transform:none;\">\r\n"
          + "                                                            Login to Your Account\r\n"
          + "                                                        </a>\r\n"
          + "                                                    </td>\r\n"
          + "                                                </tr>\r\n"
          + "                                            </table>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                    <tr>\r\n"
          + "                                        <td align=\"left\" style=\"font-size:0px;padding:10px 25px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:14px;line-height:20px;text-align:left;color:#525252;\">\r\n"
          + "                                                Best regards,<br><br> Csaba Kissi<br>Elerion ltd., CEO and Founder<br>\r\n"
          + "                                                <a href=\"https://www.htmlemailtemplates.net\" style=\"color:#2F67F6\">htmlemailtemplates.net</a>\r\n"
          + "                                            </div>\r\n"
          + "\r\n"
          + "                                        </td>\r\n"
          + "                                    </tr>\r\n"
          + "\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      \r\n"
          + "      <table\r\n"
          + "         align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"width:600px;\" width=\"600\"\r\n"
          + "      >\r\n"
          + "        <tr>\r\n"
          + "          <td style=\"line-height:0px;font-size:0px;mso-line-height-rule:exactly;\">\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "        <div style=\"Margin:0px auto;max-width:600px;\">\r\n"
          + "\r\n"
          + "            <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" style=\"width:100%;\">\r\n"
          + "                <tbody>\r\n"
          + "                    <tr>\r\n"
          + "                        <td style=\"direction:ltr;font-size:0px;padding:20px 0;text-align:center;vertical-align:top;\">\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "                  <table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n"
          + "                \r\n"
          + "        <tr>\r\n"
          + "      \r\n"
          + "            <td\r\n"
          + "               style=\"vertical-align:bottom;width:600px;\"\r\n"
          + "            >\r\n"
          + "          <![endif]-->\r\n"
          + "\r\n"
          + "                            <div class=\"mj-column-per-100 outlook-group-fix\" style=\"font-size:13px;text-align:left;direction:ltr;display:inline-block;vertical-align:bottom;width:100%;\">\r\n"
          + "\r\n"
          + "                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "                                    <tbody>\r\n"
          + "                                        <tr>\r\n"
          + "                                            <td style=\"vertical-align:bottom;padding:0;\">\r\n"
          + "\r\n"
          + "                                                <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" role=\"presentation\" width=\"100%\">\r\n"
          + "\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td align=\"center\" style=\"font-size:0px;padding:0;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:300;line-height:1;text-align:center;color:#575757;\">\r\n"
          + "                                                                Some Firm Ltd, 35 Avenue. City 10115, USA\r\n"
          + "                                                            </div>\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "\r\n"
          + "                                                    <tr>\r\n"
          + "                                                        <td align=\"center\" style=\"font-size:0px;padding:10px;word-break:break-word;\">\r\n"
          + "\r\n"
          + "                                                            <div style=\"font-family:'Helvetica Neue',Arial,sans-serif;font-size:12px;font-weight:300;line-height:1;text-align:center;color:#575757;\">\r\n"
          + "                                                                <a href=\"\" style=\"color:#575757\">Unsubscribe</a> from our emails\r\n"
          + "                                                            </div>\r\n"
          + "\r\n"
          + "                                                        </td>\r\n"
          + "                                                    </tr>\r\n"
          + "\r\n"
          + "                                                </table>\r\n"
          + "\r\n"
          + "                                            </td>\r\n"
          + "                                        </tr>\r\n"
          + "                                    </tbody>\r\n"
          + "                                </table>\r\n"
          + "\r\n"
          + "                            </div>\r\n"
          + "\r\n"
          + "                            <!--[if mso | IE]>\r\n"
          + "            </td>\r\n"
          + "          \r\n"
          + "        </tr>\r\n"
          + "      \r\n"
          + "                  </table>\r\n"
          + "                <![endif]-->\r\n"
          + "                        </td>\r\n"
          + "                    </tr>\r\n"
          + "                </tbody>\r\n"
          + "            </table>\r\n"
          + "\r\n"
          + "        </div>\r\n"
          + "\r\n"
          + "\r\n"
          + "        <!--[if mso | IE]>\r\n"
          + "          </td>\r\n"
          + "        </tr>\r\n"
          + "      </table>\r\n"
          + "      <![endif]-->\r\n"
          + "\r\n"
          + "\r\n"
          + "    </div>\r\n"
          + "\r\n"
          + "</body>\r\n"
          + "\r\n"
          + "</html>", "text/html; charset=UTF-8");
      // send the message
      Transport.send(mess);

      isSend = true;

    } catch (Exception e) {
      e.printStackTrace();
    }
    return isSend;
  }
}
